### ISSUE TITLE
Improve Python-only library (checklist)

### ISSUE THREAD

**Issue by cwschilly** [Pressio/pressio-linalg#6]
- [x] 1. need to add constraints and errrors for exmple where we we accept vectors

```py
def _basic_max_via_python(vec, comm):
	rank = vec.ndim
	if (rank != 1):
		throw errro saying that this is currently supported for a rank1 array 
```

- [x] 2. avoid gathering/broadcasting: 

```py
def _basic_max_via_python(vec, comm):
    global_max = comm.bcast(global_max, root=0)
    # ...
    data = comm.gather(local_max, root=0)
```
if we do this, it is going to be REALLY BAD performance. 
What we need to do is to use native reduction calls in MPI to find the global max.

- [x] 3. similarly for the min function 

- [x] 4. `_basic_product_via_python`:

	- need to add checks for ranks and checks that sizes are compatible

- [x] 5. remove unused functions or things that are not needed:

```
def _basic_backend_id_via_python(vec):
    status = "Using only Python"
    return status

def _basic_print_comm(comm):
    print("Python received comm")
    return MPI._addressof(comm)

try:
  ...
except ImportError as e:
    backend_id = _basic_backend_id_via_python
    print_comm = _basic_print_comm

```
where do you need these? 
Even if you use these somehow, we need to make them only private. 
So what you can do is to create a module inside that is clearly only a module containing 
private functions but we do not expose these.

- [x] 6. for the code involving bindings, please move all of it (except fort he stuff inside the cmake thing) 

to a new branch so we can just keep going with the pure python impl for now until that is ready

**Comment by cwschilly** [comment]
@fnrizzi These changes have been pushed to main
